-- Tạo database
CREATE DATABASE K22cnt3_DinhCongDinh_2210900095_Project3_db;
USE K22cnt3_DinhCongDinh_2210900095_Project3_db;

-- Bảng lưu thông tin căn cước công dân
CREATE TABLE DCD_CongDan (
    DCD_CCCD VARCHAR(12) PRIMARY KEY,
    DCD_HoTen VARCHAR(100) NOT NULL,
    DCD_NgaySinh DATE NOT NULL,
    DCD_GioiTinh ENUM('NAM', 'NỮ', 'KHÁC') NOT NULL,
    DCD_SoDienThoai VARCHAR(15) UNIQUE,
    DCD_Email VARCHAR(100) UNIQUE,
    DCD_DiaChi TEXT NOT NULL,
    DCD_NgayCap DATE NOT NULL,
    DCD_NgayHetHan DATE,
    DCD_NgayTao TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Bảng tài khoản
CREATE TABLE DCD_TaiKhoan (
    DCD_SoDienThoai VARCHAR(15) PRIMARY KEY,
    DCD_CCCD VARCHAR(12) UNIQUE NOT NULL,
    DCD_MatKhau VARCHAR(100) NOT NULL,
    DCD_VaiTro ENUM('QUAN_TRI', 'NGUOI_DUNG') NOT NULL DEFAULT 'NGUOI_DUNG',
    DCD_TrangThai ENUM('HOAT_DONG', 'KHOA') DEFAULT 'HOAT_DONG',
    DCD_NgayTao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (DCD_CCCD) REFERENCES DCD_CongDan(DCD_CCCD) ON DELETE CASCADE
);

-- Bảng yêu cầu cấp lại căn cước công dân
CREATE TABLE DCD_YeuCauCapLai (
    DCD_MaYeuCau INT AUTO_INCREMENT PRIMARY KEY,
    DCD_CCCD VARCHAR(12) NOT NULL,
    DCD_LoaiYeuCau ENUM('MOI', 'CAP_LAI', 'MAT') NOT NULL,
    DCD_TrangThai ENUM('CHO_DUYET', 'DA_DUYET', 'TU_CHOI') DEFAULT 'CHO_DUYET',
    DCD_TrangThaiGiaoHang ENUM('CHUA_GIAO', 'DANG_GIAO', 'DA_NHAN') DEFAULT 'CHUA_GIAO',
    DCD_TenNguoiNhan VARCHAR(100) NOT NULL,
    DCD_SoDienThoaiNhan VARCHAR(15) NOT NULL,
    DCD_DiaChiNhan TEXT NOT NULL,
    DCD_NgayTao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DCD_NgayCapNhat TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (DCD_CCCD) REFERENCES DCD_CongDan(DCD_CCCD) ON DELETE CASCADE
);

-- Bảng yêu cầu chỉnh sửa thông tin
CREATE TABLE DCD_YeuCauChinhSua (
    DCD_MaYeuCau INT AUTO_INCREMENT PRIMARY KEY,
    DCD_CCCD VARCHAR(12) NOT NULL,
    DCD_TruongCanSua ENUM('DCD_SoDienThoai', 'DCD_Email') NOT NULL,
    DCD_GiaTriMoi VARCHAR(100) NOT NULL,
    DCD_TrangThai ENUM('CHO_DUYET', 'DA_DUYET', 'TU_CHOI') DEFAULT 'CHO_DUYET',
    DCD_NgayTao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DCD_NgayCapNhat TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (DCD_CCCD) REFERENCES DCD_CongDan(DCD_CCCD) ON DELETE CASCADE
);

-- Bảng yêu cầu đổi mật khẩu
CREATE TABLE DCD_YeuCauDoiMatKhau (
    DCD_MaYeuCau INT AUTO_INCREMENT PRIMARY KEY,
    DCD_SoDienThoai VARCHAR(15) NOT NULL,
    DCD_MatKhauMoi VARCHAR(100) NOT NULL,
    DCD_TrangThai ENUM('CHO_DUYET', 'HOAN_THANH') DEFAULT 'CHO_DUYET',
    DCD_NgayTao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (DCD_SoDienThoai) REFERENCES DCD_TaiKhoan(DCD_SoDienThoai) ON DELETE CASCADE
);

-- Thêm dữ liệu mẫu

-- Công dân mẫu
INSERT INTO DCD_CongDan (DCD_CCCD, DCD_HoTen, DCD_NgaySinh, DCD_GioiTinh, DCD_SoDienThoai, DCD_Email, DCD_DiaChi, DCD_NgayCap, DCD_NgayHetHan)
VALUES 
('001122334455', 'Nguyen Van A', '1990-05-15', 'NAM', '0987654321', 'nguyenvana@example.com', 'Ha Noi', '2020-01-10', '2030-01-10'),
('002233445566', 'Tran thi B', '1995-08-22', 'NỮ', '0978123456', 'tranthib@example.com', 'Ho Chi Minh', '2021-05-20', '2031-05-20');

-- Tài khoản mẫu
INSERT INTO DCD_TaiKhoan (DCD_SoDienThoai, DCD_CCCD, DCD_MatKhau, DCD_VaiTro, DCD_TrangThai)
VALUES 
('0987654321', '001122334455', '123456', 'QUAN_TRI', 'HOAT_DONG'),
('0978123456', '002233445566', '654321', 'NGUOI_DUNG', 'HOAT_DONG');

-- Yêu cầu cấp lại CCCD
INSERT INTO DCD_YeuCauCapLai (DCD_CCCD, DCD_LoaiYeuCau, DCD_TrangThai, DCD_TrangThaiGiaoHang, DCD_TenNguoiNhan, DCD_SoDienThoaiNhan, DCD_DiaChiNhan)
VALUES 
('002233445566', 'CAP_LAI', 'CHO_DUYET', 'CHUA_GIAO', 'Tran thi B', '0978123456', 'TP. Hồ Chí Minh');

-- Yêu cầu chỉnh sửa thông tin
INSERT INTO DCD_YeuCauChinhSua (DCD_CCCD, DCD_TruongCanSua, DCD_GiaTriMoi, DCD_TrangThai)
VALUES 
('001122334455', 'DCD_SoDienThoai', '0911222333', 'CHO_DUYET');

-- Yêu cầu đổi mật khẩu
INSERT INTO DCD_YeuCauDoiMatKhau (DCD_SoDienThoai, DCD_MatKhauMoi, DCD_TrangThai)
VALUES 
('0987654321', 'newpass123', 'CHO_DUYET');
SELECT * FROM DCD_TaiKhoan;


